// SPDX-License-Identifier: GPL-3.0-or-later
// Download records and the rules every download must satisfy before a single byte is written.
#pragma once

#include <cstdint>
#include <filesystem>
#include <optional>
#include <string>
#include <string_view>

#include "akeno/core/Result.hpp"
#include "akeno/mods/Catalog.hpp"
#include "akeno/providers/IModProvider.hpp"

namespace akeno::downloads {

enum class DownloadState {
    Queued,       // waiting for its turn
    Downloading,  // transferring (or waiting before an automatic retry)
    Paused,       // stopped by the user; the partial file is kept
    Verifying,    // checking size and SHA-256
    Completed,    // verified; the file is ready for the next step
    Failed,       // stopped with an error; see DownloadRecord::error
};

std::string_view toString(DownloadState state) noexcept;
std::optional<DownloadState> parseDownloadState(std::string_view text) noexcept;

// What to download. Built from a provider's DownloadTicket and the mod details.
struct DownloadRequest {
    providers::ModRef mod;
    std::string displayName;    // shown in the Downloads tab
    std::string modVersion;
    std::string gameTitleId;    // the installed game it was requested for (may be empty)
    std::string gameVersion;
    std::string compatibility;  // label at request time, e.g. "VERIFIED" (informational)
    std::string url;            // https, or http to this console for local testing
    std::uint64_t expectedSize = 0;
    std::string expectedSha256; // lower-case hex, required
    mods::ArchiveFormat format = mods::ArchiveFormat::Unknown;
};

struct DownloadRecord {
    std::string id;             // 16 lower-case hex digits generated by Akeno; also the file name
    DownloadRequest request;
    DownloadState state = DownloadState::Queued;
    std::uint64_t bytesDone = 0;
    int attempts = 0;           // automatic attempts of the current run
    std::string error;          // user-facing reason of the last failure
    std::string createdAt;
    std::string updatedAt;
    std::string completedAt;
};

// Live information that is not stored.
struct DownloadProgress {
    double bytesPerSecond = 0.0;
    std::optional<double> secondsLeft;
    std::optional<double> retryInSeconds;  // waiting before an automatic retry
    std::uint64_t verifiedBytes = 0;       // while verifying
};

struct DownloadInfo {
    DownloadRecord record;
    DownloadProgress progress;
};

// Validates a request: allowed address, known size within limits, SHA-256 present, known archive
// format, sane names. Nothing is downloaded for a request that fails this check.
Status validateRequest(const DownloadRequest& request);

bool isValidDownloadId(std::string_view id) noexcept;

// File names are derived only from the generated id and the archive format, never from the
// server or the catalogue.
std::string_view fileExtension(mods::ArchiveFormat format) noexcept;
std::filesystem::path partialPath(const std::filesystem::path& directory, std::string_view id);
std::filesystem::path finalPath(const std::filesystem::path& directory, std::string_view id,
                                mods::ArchiveFormat format);
// True for names Akeno itself creates in the downloads folder ("<id>.partial", "<id>.zip", ...).
bool isDownloadFileName(std::string_view name, std::string* id = nullptr) noexcept;

// Parses "bytes <first>-<last>/<total>" (RFC 9110 Content-Range for a satisfied range).
struct ContentRange {
    std::uint64_t first = 0;
    std::uint64_t last = 0;
    std::optional<std::uint64_t> total;  // nullopt for "*"
};
std::optional<ContentRange> parseContentRange(std::string_view value) noexcept;

}  // namespace akeno::downloads
