// SPDX-License-Identifier: GPL-3.0-or-later
// The download engine (Phase 3). One transfer at a time on its own worker thread:
//
//   queued -> downloading -> verifying -> completed
//                 |   ^           |
//                 v   |           v
//              paused/failed   failed (checksum mismatch: the file is deleted)
//
// Every file is written to <downloads>/<id>.partial, where <id> is generated by Akeno, and only
// renamed to <id>.<format> after its size and SHA-256 match. Interrupted transfers resume with
// an HTTP range request; a server that answers with anything but the exact range asked for
// starts the file again from zero. Nothing here touches game data.
#pragma once

#include <chrono>
#include <condition_variable>
#include <cstdint>
#include <filesystem>
#include <functional>
#include <mutex>
#include <optional>
#include <string>
#include <thread>
#include <vector>

#include "akeno/core/Limits.hpp"
#include "akeno/core/Result.hpp"
#include "akeno/core/Tasks.hpp"
#include "akeno/database/Database.hpp"
#include "akeno/downloads/DownloadTypes.hpp"
#include "akeno/network/Http.hpp"
#include "akeno/security/SafeFs.hpp"

namespace akeno::downloads {

struct DownloadManagerOptions {
    std::filesystem::path directory;  // the application's downloads folder
    // Free space that must remain after a download (limits.hpp: 2 GiB).
    std::uint64_t storageReserve = limits::kStorageSafetyReserveBytes;
    // Waits before the automatic retries of transient network errors.
    std::vector<std::chrono::milliseconds> retryDelays{std::chrono::seconds(2), std::chrono::seconds(5),
                                                       std::chrono::seconds(15)};
    std::uint64_t syncInterval = 8ull * 1024 * 1024;  // fsync the partial file this often
    long connectTimeoutMs = 10000;
    long totalTimeoutMs = 12L * 60 * 60 * 1000;       // stalls are caught by the low-speed limit
    // Free-space query; replaceable in tests.
    std::function<Result<security::StorageSpace>(const std::filesystem::path&)> storageQuery;
};

class DownloadManager {
public:
    DownloadManager(network::IHttpClient& http, const security::SafeFs& fs, database::Database* db,
                    DownloadManagerOptions options);
    ~DownloadManager();
    DownloadManager(const DownloadManager&) = delete;
    DownloadManager& operator=(const DownloadManager&) = delete;

    // Loads stored downloads, reconciles them with the files on disk, removes files Akeno
    // created that no record refers to, and starts the worker. Idempotent.
    Status start();
    // Stops the worker. An active transfer is interrupted and continues on the next start.
    void stop();
    bool started() const;

    struct Enqueued {
        std::string id;
        bool alreadyPresent = false;  // the same file was already in the list
    };
    Result<Enqueued> enqueue(DownloadRequest request);

    Status pause(const std::string& id);   // queued or downloading -> paused (partial kept)
    Status resume(const std::string& id);  // paused or failed -> queued
    Status remove(const std::string& id);  // cancels if active; deletes its files and record

    std::vector<DownloadInfo> snapshot() const;
    std::optional<DownloadInfo> find(const std::string& id) const;
    std::optional<DownloadInfo> findForMod(const providers::ModRef& mod, const std::string& version) const;
    // The verified file of a completed download.
    Result<std::filesystem::path> completedFile(const std::string& id) const;
    const std::filesystem::path& directory() const { return options_.directory; }

    // Called on the worker thread whenever something changed (progress at most ~4 times a
    // second). It must not block; typically it posts to the UI thread.
    void setListener(std::function<void()> listener);

private:
    struct Entry {
        DownloadRecord record;
        DownloadProgress progress;
        std::chrono::steady_clock::time_point sampleTime;
        std::uint64_t sampleBytes = 0;
    };
    enum class Interrupt { None, Pause, Remove, Stop };
    enum class Outcome { Completed, Failed, Interrupted };
    struct Failure {
        Error error;
        bool retryable = false;
        bool discardPartial = false;
    };

    void run();
    Outcome process(const DownloadRecord& job, const CancellationToken& cancel, std::string& failure);
    std::optional<Failure> transferOnce(const DownloadRecord& job, const CancellationToken& cancel);
    bool waitInterruptible(std::chrono::milliseconds delay, const CancellationToken& cancel);

    Entry* findLocked(const std::string& id);
    const Entry* findLocked(const std::string& id) const;
    void persistLocked(const DownloadRecord& record);
    void touchLocked(DownloadRecord& record);
    void removeFilesLocked(const DownloadRecord& record);
    void reportProgress(const std::string& id, std::uint64_t bytes, bool verifying);
    void notify();
    std::string newIdLocked();

    network::IHttpClient& http_;
    const security::SafeFs& fs_;
    database::Database* db_;
    DownloadManagerOptions options_;

    mutable std::mutex mutex_;
    std::condition_variable wake_;
    std::vector<Entry> entries_;
    std::thread worker_;
    bool started_ = false;
    bool stopping_ = false;
    std::string activeId_;
    Interrupt interrupt_ = Interrupt::None;
    CancellationToken activeCancel_;
    std::function<void()> listener_;
    std::chrono::steady_clock::time_point lastNotify_;
    std::uint64_t idCounter_ = 0;
};

}  // namespace akeno::downloads
