// SPDX-License-Identifier: GPL-3.0-or-later
// Local file names are always generated by Akeno, never taken from servers or archives.
#pragma once

#include <string>
#include <string_view>

namespace akeno::security {

// A single path component made only of [A-Za-z0-9._-], 1..128 bytes, not starting with '.'
// and not "." or "..".
bool isSafeFileComponent(std::string_view name) noexcept;

// Maps arbitrary text to a safe component: unsupported bytes become '_', leading dots are
// dropped, length is capped at 128. Returns `fallback` if nothing usable remains.
std::string toSafeFileComponent(std::string_view text, std::string_view fallback = "item");

}  // namespace akeno::security
