# SPDX-License-Identifier: GPL-3.0-or-later
# Generates a C++ source file that embeds INPUT as a byte array and exposes it through
# FUNCTION in namespace akeno::embedded.
#
#   cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DFUNCTION=<name> -DKIND=<bytes|text> -P EmbedFile.cmake
#
# KIND=text returns std::string_view, KIND=bytes returns std::span<const unsigned char>.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED FUNCTION OR NOT DEFINED KIND)
    message(FATAL_ERROR "EmbedFile.cmake: INPUT, OUTPUT, FUNCTION and KIND are required")
endif()

file(READ "${INPUT}" content HEX)
string(LENGTH "${content}" hex_length)
math(EXPR byte_count "${hex_length} / 2")
# Two hex digits per byte -> "0xNN," and a line break every 32 bytes.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${content}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" bytes "${bytes}")

if(KIND STREQUAL "text")
    set(accessor "std::string_view ${FUNCTION}() { return {reinterpret_cast<const char*>(kData), ${byte_count}}; }")
else()
    set(accessor "std::span<const unsigned char> ${FUNCTION}() { return {kData, ${byte_count}}; }")
endif()

file(WRITE "${OUTPUT}.tmp"
"// Generated by cmake/EmbedFile.cmake from ${INPUT}. Do not edit.
#include <cstddef>
#include <span>
#include <string_view>

namespace {
alignas(16) const unsigned char kData[] = {
${bytes}
0x00};
}  // namespace

namespace akeno::embedded {
${accessor}
}  // namespace akeno::embedded
")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
